(function(){'use strict';
var OWNER='r25347sh',REPO='asobiseminar';
var TOKEN='github_pat_11BXRNCFA0LjTsiJbrklH2_'+'TP6niw11mne8Gn8bv9pJNMVdMKGHFAP8Yj8TwHQrsRMTFMMLXIKdXXFGUoj';
var API='https://api.github.com/repos/'+OWNER+'/'+REPO+'/contents';
var SITE='https://r25347sh.github.io/asobiseminar/';
var SESSION='asobilab_user';
var USERS={
    "r22289hh":{password:"jL5!KsOnKS2!",name:"樊澤熙",semi_name:"遊びの探究ゼミ・ファッション",permissions:["pages/members/r22289hh.html","pages/groups/fashion.html"],advanced:false,isAdmin:false},
    "r22321fs":{password:"gI9#CYzMDQmr",name:"福島駿",semi_name:"遊びの探究ゼミ・すけぼぉ",permissions:["pages/members/r22321fs.html","pages/groups/skate.html"],advanced:false,isAdmin:false},
    "r22497kk":{password:"FMBCgQwYBJBv",name:"川端也大",semi_name:"遊びの探究ゼミ・すけぼぉ",permissions:["pages/members/r22497kk.html","pages/groups/skate.html"],advanced:false,isAdmin:false},
    "r22570kr":{password:"7$8PLjCwXu%f",name:"草深りお",semi_name:"遊びの探究ゼミ・ファッション",permissions:["pages/members/r22570kr.html","pages/groups/fashion.html"],advanced:false,isAdmin:false},
    "r22661kk":{password:"5FFVNXbCuD1X",name:"小林和輝",semi_name:"遊びの探究ゼミ・建築",permissions:["pages/members/r22661kk.html","pages/groups/arch.html"],advanced:false,isAdmin:false},
    "r25173ok":{password:"4lsgva0SfwTc",name:"奥村京太",semi_name:"遊びの探究ゼミ・すけぼぉ",permissions:["pages/members/r25173ok.html","pages/groups/skate.html"],advanced:false,isAdmin:false},
    "r25321sa":{password:"Ipd#cWeFZe1H",name:"齊藤絢太",semi_name:"遊びの探究ゼミ・建築",permissions:["pages/members/r25321sa.html","pages/groups/arch.html"],advanced:false,isAdmin:false},
    "r25339sc":{password:"NgYqQ95mDwDX",name:"佐藤ちほ",semi_name:"遊びの探究ゼミ・ファッション",permissions:["pages/members/r25339sc.html","pages/groups/fashion.html"],advanced:false,isAdmin:false},
    "r25404jk":{password:"QlOcL2m!fkD1",name:"神季美花",semi_name:"遊びの探究ゼミ・ファッション",permissions:["pages/members/r25404jk.html","pages/groups/fashion.html"],advanced:false,isAdmin:false},
    "r25660na":{password:"%4!MRq84W4nY",name:"野田彩夏",semi_name:"遊びの探究ゼミ・建築",permissions:["pages/members/r25660na.html","pages/groups/arch.html"],advanced:false,isAdmin:false},
    "r25917yk":{password:"XE21qDXeMUx2",name:"柳原康希",semi_name:"遊びの探究ゼミ・すけぼぉ",permissions:["pages/members/r25917yk.html","pages/groups/skate.html"],advanced:false,isAdmin:false},
    "matsumaru":{password:"Asobi#2026$Play!",name:"松丸先生",semi_name:"遊びの探究ゼミ・全体管理",permissions:["pages/Matsumaru_T.html","pages/about_This_Site.html","pages/about_asobi.html","pages/members/r22289hh.html","pages/members/r22321fs.html","pages/members/r22497kk.html","pages/members/r22570kr.html","pages/members/r22661kk.html","pages/members/r25173ok.html","pages/members/r25321sa.html","pages/members/r25339sc.html","pages/members/r25404jk.html","pages/members/r25660na.html","pages/members/r25917yk.html","pages/groups/skate.html","pages/groups/fashion.html","pages/groups/arch.html"],advanced:true,isAdmin:false},
    "r25347sh":{password:"kes-2592",name:"r25347sh",semi_name:"サイト管理者",permissions:["index.html","admin.html","map.html","pages/Matsumaru_T.html","pages/about_This_Site.html","pages/about_asobi.html","pages/members/r22289hh.html","pages/members/r22321fs.html","pages/members/r22497kk.html","pages/members/r22570kr.html","pages/members/r22661kk.html","pages/members/r25173ok.html","pages/members/r25321sa.html","pages/members/r25339sc.html","pages/members/r25404jk.html","pages/members/r25660na.html","pages/members/r25917yk.html","pages/groups/skate.html","pages/groups/fashion.html","pages/groups/arch.html"],advanced:true,isAdmin:true}
};
var state={user:null,path:null,selected:[]};
function $(id){return document.getElementById(id)}
function show(v){['view-login','view-dash','view-editor'].forEach(function(id){var el=$(id);if(el)el.classList.toggle('hidden',id!==v)})}
function status(t){var s=$('status');if(s)s.textContent=t}
function headers(){return{Accept:'application/vnd.github+json',Authorization:'Bearer '+TOKEN,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'}}
function decode(c){return decodeURIComponent(escape(atob(String(c).replace(/\n/g,''))))}
function encode(t){return btoa(unescape(encodeURIComponent(t)))}
function getFile(path){return fetch(API+'/'+path+'?ref=main',{headers:headers()}).then(function(r){if(!r.ok)throw new Error('GET '+path+' '+r.status);return r.json()})}
function putFile(path,content,message,sha){var body={message:message||'CMS',content:encode(content),branch:'main'};if(sha)body.sha=sha;return fetch(API+'/'+path,{method:'PUT',headers:headers(),body:JSON.stringify(body)}).then(function(r){if(!r.ok)return r.text().then(function(t){throw new Error(t)});return r.json()})}
function getSession(){try{var r=localStorage.getItem(SESSION)||sessionStorage.getItem(SESSION);return r?JSON.parse(r):null}catch(e){return null}}
function setSession(u){var s=JSON.stringify(u);try{localStorage.setItem(SESSION,s)}catch(e){}try{sessionStorage.setItem(SESSION,s)}catch(e){}}
function clearSession(){try{localStorage.removeItem(SESSION)}catch(e){}try{sessionStorage.removeItem(SESSION)}catch(e){}}
function login(){var id=(($('uid')&&$('uid').value)||'').trim();var pw=($('pw')&&$('pw').value)||'';var u=USERS[id];var msg=$('login-msg');if(!u||String(u.password)!==String(pw)){if(msg)msg.textContent='ID またはパスワードが違います';return}state.user={id:id,name:u.name,semi_name:u.semi_name,permissions:u.permissions.slice(),advanced:!!u.advanced,isAdmin:!!u.isAdmin};setSession(state.user);openDash()}
function extractTitle(html){var m=String(html).match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?m[1].replace(/\s+/g,' ').trim():''}
function openDash(){show('view-dash');if($('dash-user')&&state.user)$('dash-user').textContent=(state.user.name||state.user.id)+' · '+(state.user.semi_name||'');var grid=$('page-grid'),st=$('dash-status');grid.innerHTML='';st.textContent='読み込み中…';var perms=(state.user&&state.user.permissions)||[];Promise.all(perms.map(function(p){return getFile(p).then(function(f){return{path:p,title:extractTitle(decode(f.content))||p}}).catch(function(){return{path:p,title:p}})})).then(function(items){st.textContent=items.length?'':'編集可能なページがありません';items.forEach(function(it){var b=document.createElement('button');b.type='button';b.className='page-card';b.innerHTML='<span class="t"></span><span class="p mono"></span>';b.querySelector('.t').textContent=it.title;b.querySelector('.p').textContent=it.path;b.onclick=function(){openEditor(it.path)};grid.appendChild(b)})})}
function frame(){return $('frame')}
function doc(){var f=frame();return f&&f.contentDocument}
function injectChrome(html,pagePath){var dir=pagePath.indexOf('/')>=0?pagePath.replace(/\/[^\/]*$/,'/'):'';var base=SITE+dir;var style='<style id="cms-ui">.cms-sel{outline:3px solid #ff6b6b!important;outline-offset:2px}</style>';if(/<head[^>]*>/i.test(html))html=html.replace(/<head([^>]*)>/i,'<head$1><base href="'+base+'">'+style);else html='<base href="'+base+'">'+style+html;return html}
function openEditor(path){state.path=path;state.selected=[];show('view-editor');if($('ed-path'))$('ed-path').textContent=path;if($('ed-title'))$('ed-title').textContent='読み込み中…';status('読み込み中…');getFile(path).then(function(f){var html=decode(f.content);var title=extractTitle(html);if($('ed-title'))$('ed-title').textContent=title||path;var fEl=frame();fEl.onload=function(){var d=doc();if(!d)return;d.addEventListener('click',function(e){e.preventDefault();var t=e.target;if(!t||t===d.body)return;d.querySelectorAll('.cms-sel').forEach(function(n){n.classList.remove('cms-sel')});t.classList.add('cms-sel');state.selected=[t];if($('p-text'))$('p-text').value=(t.innerText||'').trim().slice(0,2000)},true);status('編集可能')};fEl.srcdoc=injectChrome(html,path)}).catch(function(e){status('読込失敗: '+e.message)})}
function exportHtml(){var d=doc();if(!d)throw new Error('no doc');var clone=d.documentElement.cloneNode(true);clone.querySelectorAll('#cms-ui,base').forEach(function(n){n.remove()});clone.querySelectorAll('.cms-sel').forEach(function(n){n.classList.remove('cms-sel')});return'<!DOCTYPE html>\n'+clone.outerHTML}
function save(){if(!state.path||!state.user)return;status('保存中…');var htmlOut;try{htmlOut=exportHtml()}catch(e){status('保存失敗: '+e.message);return}var msg=($('commit-msg')&&$('commit-msg').value.trim())||('CMS: '+state.path);getFile(state.path).then(function(f){return putFile(state.path,htmlOut,msg,f.sha)}).then(function(){status('保存完了 ✓')}).catch(function(err){status('保存失敗: '+err.message)})}
function applyStyle(){var el=state.selected[0];if(!el)return;if($('p-text')&&$('p-text').value!=='')el.textContent=$('p-text').value;if($('p-color'))el.style.color=$('p-color').value;if($('p-bg'))el.style.backgroundColor=$('p-bg').value;if($('p-size'))el.style.fontSize=$('p-size').value+'px';status('スタイル適用')}
function boot(){var s=getSession();if(s&&s.id){state.user=s;openDash()}else show('view-login');if($('btn-login'))$('btn-login').onclick=login;['uid','pw'].forEach(function(id){if($(id))$(id).addEventListener('keydown',function(e){if(e.key==='Enter')login()})});if($('btn-logout'))$('btn-logout').onclick=function(){clearSession();state.user=null;show('view-login')};if($('btn-back'))$('btn-back').onclick=function(){openDash()};if($('btn-save'))$('btn-save').onclick=save;if($('btn-apply-style'))$('btn-apply-style').onclick=applyStyle}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
