/** Asobi Terminal v1.3 — special panels (syntax-fixed) */
(function(){'use strict';
if(window.__ASOBI_TERMINAL_BOOTED__)return;window.__ASOBI_TERMINAL_BOOTED__=true;
const BASE='/asobiseminar',SU_PASSWORD='kanrishakengen',SUDO_MS=5*60*1000,THEME_KEY='asobi-term-theme';
const THEMES=['default','matrix','ubuntu','macos','powershell','cyber','cmd','dracula','nord','solarized','monokai','light'];
const LOG_BUFFER_MAX=200,NET_BUFFER_MAX=100;
const FS_TREE={'404.html':'file','favicon.svg':'file','index.html':'file','index2.html':'file','memo.md':'file','samplecss.css':'file','settings.html':'file','sitemap.html':'file','themecolor.json':'file','variable.css':'file','テーマのメモ.txt':'file',MENU:{'MENU.css':'file','MENU.js':'file'},css:{'404.css':'file','aboutsite.css':'file','asobi-play.css':'file','groupsIndex.css':'file','index-main.css':'file','members.css':'file','one.css':'file','playground.css':'file','programmer.css':'file','settings.css':'file','style.css':'file','three.css':'file','title.css':'file','two.css':'file'},gaibu:{'unpkg.css':'file'},js:{'404.js':'file','asobi-play.js':'file','autovalue.js':'file','load-css.js':'file','playground.js':'file','setThemeColor.js':'file'},json:{'autovalue.json':'file'},subpages:{'aboutsite.html':'file','gallery.html':'file','members.html':'file','playground.html':'file',groups:{'englishgame.html':'file','index.html':'file','one.html':'file','programmer.html':'file','three.html':'file','two.html':'file'}},terminal:{'terminal.css':'file','terminal.js':'file'}};
const PAGE_MAP={home:BASE+'/index.html',index:BASE+'/index.html',index2:BASE+'/index2.html',top:BASE+'/index.html',playground:BASE+'/subpages/playground.html',play:BASE+'/subpages/playground.html',members:BASE+'/subpages/members.html',member:BASE+'/subpages/members.html',groups:BASE+'/subpages/groups/index.html',group:BASE+'/subpages/groups/index.html',about:BASE+'/subpages/aboutsite.html',aboutsite:BASE+'/subpages/aboutsite.html',settings:BASE+'/settings.html',setting:BASE+'/settings.html',gallery:BASE+'/subpages/gallery.html',one:BASE+'/subpages/groups/one.html',two:BASE+'/subpages/groups/two.html',three:BASE+'/subpages/groups/three.html',programmer:BASE+'/subpages/groups/programmer.html',prog:BASE+'/subpages/groups/programmer.html',englishgame:BASE+'/subpages/groups/englishgame.html',english:BASE+'/subpages/groups/englishgame.html',sitemap:BASE+'/sitemap.html',map:BASE+'/sitemap.html','404':BASE+'/404.html',notfound:BASE+'/404.html',favicon:BASE+'/favicon.svg',theme:BASE+'/themecolor.json',themecolor:BASE+'/themecolor.json',memo:BASE+'/memo.md',github:'https://github.com/r25347sh/asobiseminar',repo:'https://github.com/r25347sh/asobiseminar',gh:'https://github.com/r25347sh/asobiseminar'};
let isRoot=false,sudoUntil=0,history=[],histIdx=-1,awaitingPassword=false;
let panel,bodyEl,inputEl,promptEl,badgeEl,toggleBtn,currentTheme='default';
let consolePanel,consoleBody,consoleInput,consoleHooked=false,logBuffer=[];
let storagePanel,storageBody,networkPanel,networkBody,netBuffer=[],netHooked=false;
let domPanel,domBody,domInput,infoPanel,infoBody,palettePanel,paletteBody;
let keysPanel,keysBody,keysHooked=false,keyLog=[];
const origConsole={log:console.log.bind(console),info:console.info.bind(console),warn:console.warn.bind(console),error:console.error.bind(console),debug:console.debug?console.debug.bind(console):console.log.bind(console)};
const origFetch=window.fetch.bind(window);
function hasElevated(){return isRoot||Date.now()<sudoUntil;}
function promptText(){return hasElevated()?'root@asobi#':'guest@asobi$';}
function updatePromptUI(){if(!promptEl||!badgeEl)return;const elev=hasElevated();promptEl.textContent=promptText();promptEl.classList.toggle('is-root',elev);badgeEl.textContent=elev?(isRoot?'ROOT':'SUDO'):'guest';badgeEl.classList.toggle('is-root',elev);}
function focusInput(){if(!inputEl)return;try{inputEl.focus({preventScroll:true});}catch(e){try{inputEl.focus();}catch(e2){}}}
function appendLine(text,cls){if(!bodyEl)return;const p=document.createElement('div');p.className='asobi-term-line '+(cls||'out');p.textContent=text;bodyEl.appendChild(p);bodyEl.scrollTop=bodyEl.scrollHeight;}
function clearTerm(){if(bodyEl)bodyEl.innerHTML='';}
function applyTheme(name){const t=THEMES.includes(name)?name:'default';currentTheme=t;try{localStorage.setItem(THEME_KEY,t);}catch(e){}if(panel){if(t==='default')panel.removeAttribute('data-theme');else panel.setAttribute('data-theme',t);}}
function loadSavedTheme(){try{const s=localStorage.getItem(THEME_KEY);if(s&&THEMES.includes(s))currentTheme=s;}catch(e){}}
function buildTreeLines(node,prefix){const lines=[];const keys=Object.keys(node).sort((a,b)=>{const aDir=typeof node[a]==='object',bDir=typeof node[b]==='object';if(aDir!==bDir)return aDir?-1:1;return a.localeCompare(b,'ja');});keys.forEach((k,i)=>{const last=i===keys.length-1;const branch=last?'└── ':'├── ';const next=prefix+(last?'    ':'│   ');if(typeof node[k]==='object'){lines.push(prefix+branch+k+'/');lines.push(...buildTreeLines(node[k],next));}else lines.push(prefix+branch+k);});return lines;}
function makeToolPanel(opts){const el=document.createElement('div');el.className='asobi-tool-panel '+(opts.cls||'');el.innerHTML='<div class="asobi-tool-header"><span class="asobi-tool-label"><span>'+opts.title+'</span>'+(opts.badge?'<span class="asobi-tool-live">'+opts.badge+'</span>':'')+'</span><div class="asobi-tool-actions">'+(opts.extraBtns||'')+'<button type="button" data-act="refresh">↻</button><button type="button" data-act="close">✕</button></div></div><div class="asobi-tool-body"></div>'+(opts.footer||'');document.body.appendChild(el);const body=el.querySelector('.asobi-tool-body');el.querySelector('[data-act="close"]').addEventListener('click',function(){el.classList.remove('is-open');if(opts.onClose)opts.onClose();setTimeout(focusInput,20);});const refBtn=el.querySelector('[data-act="refresh"]');if(refBtn)refBtn.addEventListener('click',function(){if(opts.onRefresh)opts.onRefresh(body);});return{el:el,body:body};}
function openTool(ref){if(ref&&ref.el)ref.el.classList.add('is-open');}
function closeTool(ref){if(ref&&ref.el)ref.el.classList.remove('is-open');}
function stringifyArg(a){if(a===null)return'null';if(a===undefined)return'undefined';if(typeof a==='string')return a;if(typeof a==='number'||typeof a==='boolean'||typeof a==='bigint')return String(a);if(typeof a==='symbol')return a.toString();if(a instanceof Error)return a.stack||(a.name+': '+a.message);if(typeof a==='function')return'[Function'+(a.name?': '+a.name:'')+']';try{return JSON.stringify(a,function(_k,v){if(typeof v==='bigint')return v.toString()+'n';if(typeof v==='function')return'[Function]';return v;},0);}catch(e){try{return Object.prototype.toString.call(a);}catch(e2){return String(a);}}}
function iconFor(level){return level==='error'?'✕':level==='warn'?'⚠':level==='info'?'ℹ':'›';}
function pushConsoleEntry(level,args){const entry={level:level,args:args,ts:Date.now()};logBuffer.push(entry);if(logBuffer.length>LOG_BUFFER_MAX)logBuffer.shift();if(consoleBody)renderConsoleEntry(entry);}
function renderConsoleEntry(entry){if(!consoleBody)return;const el=document.createElement('div');el.className='asobi-console-entry '+entry.level;const icon=document.createElement('span');icon.className='asobi-console-icon';icon.textContent=iconFor(entry.level);el.appendChild(icon);const time=document.createElement('span');time.className='asobi-console-time';const d=new Date(entry.ts);time.textContent=d.toLocaleTimeString('ja-JP',{hour12:false})+'.'+String(d.getMilliseconds()).padStart(3,'0');el.appendChild(time);const msg=document.createElement('span');msg.className='asobi-console-msg';msg.textContent=entry.args.map(stringifyArg).join(' ');el.appendChild(msg);consoleBody.appendChild(el);consoleBody.scrollTop=consoleBody.scrollHeight;}
function hookConsole(){if(consoleHooked)return;consoleHooked=true;['log','info','warn','error','debug'].forEach(function(level){const mapLevel=level==='debug'?'log':level;console[level]=function(){const args=Array.prototype.slice.call(arguments);origConsole[level].apply(console,args);try{pushConsoleEntry(mapLevel,args);}catch(e){};};});window.addEventListener('error',function(ev){const parts=[];if(ev.message)parts.push(ev.message);if(ev.filename)parts.push('@ '+ev.filename+(ev.lineno!=null?':'+ev.lineno:''));if(ev.error&&ev.error.stack)parts.push('\n'+ev.error.stack);pushConsoleEntry('error',[parts.join(' ')||'Uncaught Error']);});window.addEventListener('unhandledrejection',function(ev){const r=ev.reason;let msg='UnhandledRejection: ';if(r instanceof Error)msg+=r.stack||(r.name+': '+r.message);else msg+=stringifyArg(r);pushConsoleEntry('error',[msg]);});pushConsoleEntry('info',['Local console attached.']);}
function ensureConsoleUI(){if(consolePanel)return;consolePanel=document.createElement('div');consolePanel.className='asobi-tool-panel asobi-console-panel';consolePanel.innerHTML='<div class="asobi-tool-header"><span class="asobi-tool-label"><span>JS Console</span><span class="asobi-tool-live">LIVE</span></span><div class="asobi-tool-actions"><button type="button" data-act="clear">clear</button><button type="button" data-act="close">✕</button></div></div><div class="asobi-tool-body asobi-console-body"></div><div class="asobi-tool-footer"><input class="asobi-console-input" placeholder="eval / 式を入力" spellcheck="false" autocomplete="off" /><button type="button" class="asobi-console-run">Run</button></div>';document.body.appendChild(consolePanel);consoleBody=consolePanel.querySelector('.asobi-console-body');consoleInput=consolePanel.querySelector('.asobi-console-input');consolePanel.querySelector('[data-act="close"]').addEventListener('click',closeLocalConsole);consolePanel.querySelector('[data-act="clear"]').addEventListener('click',function(){logBuffer=[];if(consoleBody)consoleBody.innerHTML='';});function runEval(){const code=consoleInput.value;if(!code.trim())return;pushConsoleEntry('log',['› '+code]);try{const result=(0,eval)(code);if(result!==undefined)pushConsoleEntry('info',[stringifyArg(result)]);}catch(e){pushConsoleEntry('error',[e&&e.stack?e.stack:String(e)]);}consoleInput.value='';}consolePanel.querySelector('.asobi-console-run').addEventListener('click',runEval);consoleInput.addEventListener('keydown',function(e){e.stopPropagation();if(e.key==='Enter')runEval();if(e.key==='Escape')closeLocalConsole();});}
function openLocalConsole(){ensureConsoleUI();if(consoleBody){consoleBody.innerHTML='';logBuffer.forEach(renderConsoleEntry);}consolePanel.classList.add('is-open');appendLine('JS Console を開きました','ok');if(consoleInput)setTimeout(function(){consoleInput.focus();},50);}
function closeLocalConsole(){if(consolePanel)consolePanel.classList.remove('is-open');appendLine('JS Console を閉じました','sys');setTimeout(focusInput,30);}
function renderStorage(body){body.innerHTML='';function section(title,store){const h=document.createElement('div');h.className='asobi-tool-section';h.textContent=title+' ('+store.length+')';body.appendChild(h);if(!store.length){const empty=document.createElement('div');empty.className='asobi-tool-muted';empty.textContent='(empty)';body.appendChild(empty);return;}for(let i=0;i<store.length;i++){const k=store.key(i);let v;try{v=store.getItem(k);}catch(e){v='(error)';}const row=document.createElement('div');row.className='asobi-tool-row';const keyEl=document.createElement('code');keyEl.className='asobi-tool-key';keyEl.textContent=k;const valEl=document.createElement('span');valEl.className='asobi-tool-val';valEl.textContent=v&&v.length>120?v.slice(0,120)+'…':v;const del=document.createElement('button');del.type='button';del.textContent='x';del.title='delete';del.addEventListener('click',function(){store.removeItem(k);renderStorage(body);});row.appendChild(keyEl);row.appendChild(valEl);row.appendChild(del);body.appendChild(row);}}try{section('localStorage',localStorage);}catch(e){}try{section('sessionStorage',sessionStorage);}catch(e){}}
function openStorage(){if(!storagePanel){const t=makeToolPanel({title:'Storage',badge:'LS/SS',cls:'asobi-storage-panel',onRefresh:renderStorage});storagePanel=t.el;storageBody=t.body;}renderStorage(storageBody);openTool({el:storagePanel});appendLine('Storage パネルを開きました','ok');}
function pushNet(entry){netBuffer.push(entry);if(netBuffer.length>NET_BUFFER_MAX)netBuffer.shift();if(networkBody&&networkPanel&&networkPanel.classList.contains('is-open'))renderNetwork(networkBody);}
function hookNetwork(){if(netHooked)return;netHooked=true;window.fetch=function(input,init){const url=typeof input==='string'?input:(input&&input.url?input.url:String(input));const method=(init&&init.method)||(input&&input.method)||'GET';const started=Date.now();return origFetch(input,init).then(function(res){pushNet({url:url,method:method,status:res.status,ok:res.ok,ms:Date.now()-started,ts:started});return res;}).catch(function(err){pushNet({url:url,method:method,status:0,ok:false,ms:Date.now()-started,ts:started,err:String(err&&err.message||err)});throw err;});};}
function renderNetwork(body){body.innerHTML='';if(!netBuffer.length){const empty=document.createElement('div');empty.className='asobi-tool-muted';empty.textContent='fetch ログはまだありません';body.appendChild(empty);return;}netBuffer.slice().reverse().forEach(function(e){const row=document.createElement('div');row.className='asobi-tool-row '+(e.ok?'net-ok':'net-err');const st=document.createElement('span');st.className='asobi-tool-badge';st.textContent=e.status||'ERR';const m=document.createElement('code');m.textContent=e.method;const u=document.createElement('span');u.className='asobi-tool-val';u.textContent=e.url+(e.err?' — '+e.err:'');const t=document.createElement('span');t.className='asobi-tool-muted';t.textContent=e.ms+'ms';row.appendChild(st);row.appendChild(m);row.appendChild(u);row.appendChild(t);body.appendChild(row);});}
function openNetwork(){hookNetwork();if(!networkPanel){const t=makeToolPanel({title:'Network',badge:'fetch',cls:'asobi-network-panel',onRefresh:renderNetwork,extraBtns:'<button type="button" data-act="clearnet">clear</button>'});networkPanel=t.el;networkBody=t.body;networkPanel.querySelector('[data-act="clearnet"]').addEventListener('click',function(){netBuffer=[];renderNetwork(networkBody);});}renderNetwork(networkBody);openTool({el:networkPanel});appendLine('Network パネルを開きました','ok');}
function renderDom(body,selector){body.innerHTML='';const sel=selector||'body *';let nodes;try{nodes=document.querySelectorAll(sel);}catch(e){const err=document.createElement('div');err.className='asobi-tool-err';err.textContent='Selector error: '+e.message;body.appendChild(err);return;}const info=document.createElement('div');info.className='asobi-tool-section';info.textContent=sel+' → '+nodes.length+' elements';body.appendChild(info);const max=Math.min(nodes.length,80);for(let i=0;i<max;i++){const n=nodes[i];const row=document.createElement('div');row.className='asobi-tool-row';const tag=document.createElement('code');tag.className='asobi-tool-key';let label=n.tagName?n.tagName.toLowerCase():'?';if(n.id)label+='#'+n.id;if(n.classList&&n.classList.length)label+='.'+Array.prototype.slice.call(n.classList,0,3).join('.');tag.textContent=label;const meta=document.createElement('span');meta.className='asobi-tool-muted';meta.textContent=(n.children?n.children.length:0)+' children';row.appendChild(tag);row.appendChild(meta);row.addEventListener('click',function(){try{document.querySelectorAll('.asobi-dom-hl').forEach(function(x){x.classList.remove('asobi-dom-hl');});n.classList.add('asobi-dom-hl');n.scrollIntoView({block:'center',behavior:'smooth'});}catch(e){}});body.appendChild(row);}if(nodes.length>max){const more=document.createElement('div');more.className='asobi-tool-muted';more.textContent='… and '+(nodes.length-max)+' more';body.appendChild(more);}}
function openDom(){if(!domPanel){domPanel=document.createElement('div');domPanel.className='asobi-tool-panel asobi-dom-panel';domPanel.innerHTML='<div class="asobi-tool-header"><span class="asobi-tool-label"><span>DOM</span><span class="asobi-tool-live">query</span></span><div class="asobi-tool-actions"><button type="button" data-act="close">✕</button></div></div><div class="asobi-tool-footer"><input class="asobi-dom-input" placeholder="CSS selector" spellcheck="false" /><button type="button" data-act="run">Query</button></div><div class="asobi-tool-body"></div>';document.body.appendChild(domPanel);domBody=domPanel.querySelector('.asobi-tool-body');domInput=domPanel.querySelector('.asobi-dom-input');domPanel.querySelector('[data-act="close"]').addEventListener('click',function(){closeTool({el:domPanel});document.querySelectorAll('.asobi-dom-hl').forEach(function(x){x.classList.remove('asobi-dom-hl');});setTimeout(focusInput,20);});function runQ(){renderDom(domBody,domInput.value.trim()||'body *');}domPanel.querySelector('[data-act="run"]').addEventListener('click',runQ);domInput.addEventListener('keydown',function(e){e.stopPropagation();if(e.key==='Enter')runQ();if(e.key==='Escape')closeTool({el:domPanel});});}renderDom(domBody,'body > *');openTool({el:domPanel});appendLine('DOM パネルを開きました','ok');if(domInput)setTimeout(function(){domInput.focus();},50);}
function renderInfo(body){body.innerHTML='';
var lsLen='?';try{lsLen=String(localStorage.length);}catch(e){}
var rows=[['URL',location.href],['Path',location.pathname],['UA',navigator.userAgent],['Language',navigator.language],['Online',String(navigator.onLine)],['Screen',screen.width+'x'+screen.height],['Viewport',window.innerWidth+'x'+window.innerHeight],['DPR',String(window.devicePixelRatio)],['Timezone',Intl.DateTimeFormat().resolvedOptions().timeZone],['Cookies',document.cookie?document.cookie.slice(0,80):'(none)'],['Theme',currentTheme],['localStorage keys',lsLen],['Scripts',String(document.scripts.length)],['Stylesheets',String(document.styleSheets.length)]];
rows.forEach(function(r){var row=document.createElement('div');row.className='asobi-tool-row';var k=document.createElement('code');k.className='asobi-tool-key';k.textContent=r[0];var v=document.createElement('span');v.className='asobi-tool-val';v.textContent=r[1];row.appendChild(k);row.appendChild(v);body.appendChild(row);});}
function openInfo(){if(!infoPanel){const t=makeToolPanel({title:'System Info',badge:'env',cls:'asobi-info-panel',onRefresh:renderInfo});infoPanel=t.el;infoBody=t.body;}renderInfo(infoBody);openTool({el:infoPanel});appendLine('System Info を開きました','ok');}
function renderPalette(body){body.innerHTML='';const cs=getComputedStyle(document.documentElement);const names=['--main-color','--accent-color','--balance-color','--bg-color','--text-color','--sub-color'];const h=document.createElement('div');h.className='asobi-tool-section';h.textContent='CSS Variables';body.appendChild(h);names.forEach(function(name){const val=cs.getPropertyValue(name).trim()||'(unset)';const row=document.createElement('div');row.className='asobi-tool-row';const sw=document.createElement('span');sw.className='asobi-swatch';if(val&&val!=='(unset)')sw.style.background=val;const k=document.createElement('code');k.className='asobi-tool-key';k.textContent=name;const v=document.createElement('span');v.className='asobi-tool-val';v.textContent=val;row.appendChild(sw);row.appendChild(k);row.appendChild(v);body.appendChild(row);});const h2=document.createElement('div');h2.className='asobi-tool-section';h2.textContent='Terminal themes';body.appendChild(h2);THEMES.forEach(function(t){const row=document.createElement('div');row.className='asobi-tool-row';const k=document.createElement('code');k.className='asobi-tool-key';k.textContent=t+(t===currentTheme?' ←':'');const btn=document.createElement('button');btn.type='button';btn.textContent='apply';btn.addEventListener('click',function(){applyTheme(t);renderPalette(body);appendLine('ターミナルテーマ: '+t,'ok');});row.appendChild(k);row.appendChild(btn);body.appendChild(row);});}
function openPalette(){if(!palettePanel){const t=makeToolPanel({title:'Palette',badge:'colors',cls:'asobi-palette-panel',onRefresh:renderPalette});palettePanel=t.el;paletteBody=t.body;}renderPalette(paletteBody);openTool({el:palettePanel});appendLine('Palette を開きました','ok');}
function pushKey(ev){keyLog.push({key:ev.key,code:ev.code,type:ev.type,ctrl:ev.ctrlKey,alt:ev.altKey,shift:ev.shiftKey,meta:ev.metaKey,ts:Date.now()});if(keyLog.length>80)keyLog.shift();if(keysBody&&keysPanel&&keysPanel.classList.contains('is-open'))renderKeys(keysBody);}
function hookKeys(){if(keysHooked)return;keysHooked=true;window.addEventListener('keydown',function(e){pushKey(e);},true);window.addEventListener('keyup',function(e){pushKey(e);},true);}
function renderKeys(body){body.innerHTML='';if(!keyLog.length){const empty=document.createElement('div');empty.className='asobi-tool-muted';empty.textContent='キー入力を待つ…';body.appendChild(empty);return;}keyLog.slice().reverse().forEach(function(e){const row=document.createElement('div');row.className='asobi-tool-row';const t=document.createElement('span');t.className='asobi-tool-badge';t.textContent=e.type;const k=document.createElement('code');k.className='asobi-tool-key';k.textContent=e.key;const mods=[];if(e.ctrl)mods.push('Ctrl');if(e.alt)mods.push('Alt');if(e.shift)mods.push('Shift');if(e.meta)mods.push('Meta');const m=document.createElement('span');m.className='asobi-tool-muted';m.textContent=(mods.join('+')||'')+' '+e.code;row.appendChild(t);row.appendChild(k);row.appendChild(m);body.appendChild(row);});}
function openKeys(){hookKeys();if(!keysPanel){const t=makeToolPanel({title:'Keyboard',badge:'keys',cls:'asobi-keys-panel',onRefresh:renderKeys,extraBtns:'<button type="button" data-act="clearkeys">clear</button>'});keysPanel=t.el;keysBody=t.body;keysPanel.querySelector('[data-act="clearkeys"]').addEventListener('click',function(){keyLog=[];renderKeys(keysBody);});}renderKeys(keysBody);openTool({el:keysPanel});appendLine('Keyboard パネルを開きました','ok');}
const PANEL_CMDS={console:{open:openLocalConsole,close:closeLocalConsole,clear:function(){logBuffer=[];if(consoleBody)consoleBody.innerHTML='';appendLine('console cleared','ok');}},storage:{open:openStorage,close:function(){closeTool({el:storagePanel});appendLine('Storage を閉じました','sys');}},network:{open:openNetwork,close:function(){closeTool({el:networkPanel});appendLine('Network を閉じました','sys');},clear:function(){netBuffer=[];if(networkBody)renderNetwork(networkBody);appendLine('network cleared','ok');}},dom:{open:openDom,close:function(){closeTool({el:domPanel});document.querySelectorAll('.asobi-dom-hl').forEach(function(x){x.classList.remove('asobi-dom-hl');});appendLine('DOM を閉じました','sys');}},info:{open:openInfo,close:function(){closeTool({el:infoPanel});appendLine('Info を閉じました','sys');}},sysinfo:{open:openInfo,close:function(){closeTool({el:infoPanel});}},palette:{open:openPalette,close:function(){closeTool({el:palettePanel});appendLine('Palette を閉じました','sys');}},colors:{open:openPalette,close:function(){closeTool({el:palettePanel});}},keys:{open:openKeys,close:function(){closeTool({el:keysPanel});appendLine('Keys を閉じました','sys');},clear:function(){keyLog=[];if(keysBody)renderKeys(keysBody);appendLine('keys cleared','ok');}},keyboard:{open:openKeys,close:function(){closeTool({el:keysPanel});}}};
function listPanels(){appendLine('特殊パネル一覧:','info');appendLine('  console.open|close|clear   JS console.log / エラー','out');appendLine('  storage.open|close         localStorage / sessionStorage','out');appendLine('  network.open|close|clear   fetch 監視','out');appendLine('  dom.open|close             DOM クエリ / ハイライト','out');appendLine('  info.open|close            環境・画面情報','out');appendLine('  palette.open|close         CSS変数 / テーマ切替','out');appendLine('  keys.open|close|clear      キー入力ログ','out');appendLine('例: storage.open  /  network.open  /  panels','sys');}
function handlePanelCmd(name,method){const p=PANEL_CMDS[name];if(!p)return false;const fn=p[method||'open'];if(typeof fn==='function'){fn();return true;}appendLine('用法: '+name+'.open | '+name+'.close','warn');return true;}
function cmdHelp(){appendLine('Asobi Lab. Terminal — コマンド一覧','info');appendLine('  help / clear / ls / pwd / whoami / history / echo / date / uname','out');appendLine('  open <page|url> / su / sudo / exit / logout','out');appendLine('  chaos / score / theme / term.theme','out');appendLine('  panels  → 特殊パネル一覧','out');appendLine('  console / storage / network / dom / info / palette / keys','out');appendLine('例: console.open  storage.open  network.open','sys');}
function cmdLs(){appendLine(BASE+'/','info');buildTreeLines(FS_TREE,'').forEach(function(l){appendLine(l,'out');});}
function cmdOpen(target){if(!target||target==='list'||target==='help'){appendLine('open ページ一覧:','info');const seen={};Object.keys(PAGE_MAP).sort().forEach(function(k){const u=PAGE_MAP[k];if(seen[u])return;seen[u]=true;const aliases=Object.keys(PAGE_MAP).filter(function(a){return PAGE_MAP[a]===u;}).join(', ');appendLine('  '+aliases,'out');});return;}const key=target.toLowerCase().replace(/^\/+/,'');let url=PAGE_MAP[key];if(!url){if(/^https?:\/\//i.test(target))url=target;else if(target.startsWith('/'))url=target;else if(/\.(html|svg|json|md|css|js)(\?|$)/i.test(target)||target.indexOf('/')!==-1)url=BASE+'/'+target.replace(/^\/+/,'');}if(!url){appendLine('見つかりません: '+target,'err');return;}appendLine('open → '+url,'ok');setTimeout(function(){location.href=url;},280);}
function cmdChaos(action){const ap=window.AsobiPlay;if(!ap||typeof ap.toggleChaos!=='function'){appendLine('AsobiPlay が未読込です','err');return;}if(action==='on'){ap.toggleChaos(true);appendLine('混沌モード ON','ok');}else if(action==='off'){ap.toggleChaos(false);appendLine('混沌モード OFF','ok');}else if(action==='status'||!action)appendLine('chaos: '+(document.body.classList.contains('asobi-chaos')?'ON':'OFF'),'info');else appendLine('用法: chaos.on|off|status','warn');}
function cmdScore(){const ap=window.AsobiPlay;if(ap&&typeof ap.getScore==='function')appendLine('遊びスコア: '+ap.getScore()+' pt','ok');else appendLine('遊びスコア: '+(localStorage.getItem('asobi-play-score')||'0')+' pt','ok');}
function cmdTheme(action,name){if(action==='list'||!action){fetch(BASE+'/themecolor.json').then(function(r){return r.json();}).then(function(data){const themes=data.themes||data;appendLine('利用可能なテーマ:','info');(Array.isArray(themes)?themes:[]).forEach(function(t){appendLine('  - '+(t.name||t),'out');});focusInput();}).catch(function(e){appendLine('失敗: '+(e&&e.message?e.message:e),'err');focusInput();});return;}if(action==='set'){if(!name){appendLine('用法: theme.set <name>','warn');return;}localStorage.setItem('selectedTheme',name);appendLine('テーマを設定: '+name,'ok');setTimeout(function(){location.reload();},400);return;}appendLine('用法: theme.list|set','warn');}
function cmdTermTheme(action,name){if(action==='list'||!action){appendLine('ターミナル見た目 — '+THEMES.length+' 種:','info');THEMES.forEach(function(t){appendLine('  - '+t+(t===currentTheme?' ← 現在':''),'out');});return;}if(action==='set'){if(!name||!THEMES.includes(name)){appendLine('不明: '+(name||''),'err');return;}applyTheme(name);appendLine('ターミナルテーマ: '+name,'ok');return;}if(THEMES.includes(action)){applyTheme(action);appendLine('ターミナルテーマ: '+action,'ok');return;}appendLine('用法: term.theme <name>','warn');}
function resolveDotted(parts,args){const obj=parts[0],method=parts[1],rest=parts.slice(2).concat(args);if(PANEL_CMDS[obj])return handlePanelCmd(obj,method||'open');if(obj==='chaos'){cmdChaos(method);return true;}if(obj==='theme'){cmdTheme(method,rest[0]);return true;}if(obj==='score'){cmdScore();return true;}if(obj==='term'||obj==='terminal'){if(method==='clear')clearTerm();else if(method==='close')closePanel();else if(method==='open')openPanel();else if(method==='theme'){if(!rest.length||rest[0]==='list')cmdTermTheme('list');else if(rest[0]==='set')cmdTermTheme('set',rest[1]);else cmdTermTheme(rest[0],rest[1]);}else appendLine('用法: terminal.open|close|clear|theme','warn');return true;}if(obj==='panels'||obj==='panel'){listPanels();return true;}return false;}
function executeSingle(raw){const line=String(raw||'').trim();if(!line)return;if(awaitingPassword){awaitingPassword=false;if(line===SU_PASSWORD){isRoot=true;updatePromptUI();appendLine('認証成功。root 権限を取得しました。','ok');}else appendLine('認証失敗','err');return;}if(/^sudo(\s|$)/i.test(line)){const rest=line.replace(/^sudo\s*/i,'').trim();sudoUntil=Date.now()+SUDO_MS;updatePromptUI();appendLine('[sudo] 一時権限を付与（5分）','sys');if(!rest)return;executeSingle(rest);return;}const dottedMatch=line.match(/^([a-zA-Z_][\w]*)\.([a-zA-Z_][\w.]*)(?:\s+(.*))?$/);if(dottedMatch){const obj=dottedMatch[1];const methodPath=dottedMatch[2].split('.');const argStr=(dottedMatch[3]||'').trim();const dArgs=argStr?argStr.split(/\s+/):[];if(resolveDotted([obj].concat(methodPath),dArgs))return;appendLine('不明な属性: '+obj+'.'+methodPath.join('.'),'err');return;}const tokens=[];const reTok=/"([^"]*)"|(\S+)/g;let mTok;while((mTok=reTok.exec(line))!==null)tokens.push(mTok[1]!==undefined?mTok[1]:mTok[2]);const cmd=(tokens[0]||'').toLowerCase();const args=tokens.slice(1);switch(cmd){case'help':case'?':cmdHelp();break;case'clear':case'cls':clearTerm();break;case'ls':case'tree':cmdLs();break;case'pwd':appendLine(location.pathname,'out');break;case'whoami':appendLine(hasElevated()?(isRoot?'root':'guest (sudo)'):'guest','out');break;case'history':if(!history.length)appendLine('(empty)','sys');else history.forEach(function(h,i){appendLine(String(i+1).padStart(3)+'  '+h,'out');});break;case'echo':appendLine(args.join(' '),'out');break;case'open':cmdOpen(args[0]);break;case'su':appendLine('Password:','info');awaitingPassword=true;break;case'exit':if(isRoot||Date.now()<sudoUntil){isRoot=false;sudoUntil=0;updatePromptUI();appendLine('権限を破棄しました','sys');}else closePanel();break;case'logout':isRoot=false;sudoUntil=0;updatePromptUI();appendLine('logout','sys');break;case'chaos':cmdChaos(args[0]);break;case'score':cmdScore();break;case'theme':cmdTheme(args[0],args[1]);break;case'panels':case'panel':listPanels();break;case'console':case'storage':case'network':case'dom':case'info':case'sysinfo':case'palette':case'colors':case'keys':case'keyboard':handlePanelCmd(cmd,args[0]||'open');break;case'date':appendLine(new Date().toString(),'out');break;case'uname':appendLine('AsobiLab Terminal · '+navigator.userAgent.split(' ').slice(-2).join(' '),'out');break;case'reload':appendLine('reloading…','sys');setTimeout(function(){location.reload();},200);break;default:appendLine('command not found: '+cmd,'err');appendLine('help / panels で一覧','sys');}}
function executeLine(raw){String(raw||'').split(/\s*&&\s*/).forEach(function(p){try{executeSingle(p);}catch(err){appendLine('実行エラー: '+(err&&err.message?err.message:String(err)),'err');}});}
function openPanel(){if(!panel)return;panel.classList.add('is-open');if(toggleBtn)toggleBtn.classList.add('is-active');setTimeout(focusInput,30);}
function closePanel(){if(!panel)return;panel.classList.remove('is-open');if(toggleBtn)toggleBtn.classList.remove('is-active');}
function togglePanel(){if(panel&&panel.classList.contains('is-open'))closePanel();else openPanel();}
function buildUI(){if(document.querySelector('.asobi-term-toggle'))return;toggleBtn=document.createElement('button');toggleBtn.type='button';toggleBtn.className='asobi-term-toggle';toggleBtn.title='Asobi Terminal';toggleBtn.setAttribute('aria-label','Open terminal');toggleBtn.textContent='>_';toggleBtn.addEventListener('click',function(e){e.stopPropagation();togglePanel();});document.body.appendChild(toggleBtn);panel=document.createElement('div');panel.className='asobi-term-panel';panel.innerHTML='<div class="asobi-term-header"><span class="asobi-term-title">Asobi Terminal</span><span class="asobi-term-badge">guest</span><div class="asobi-term-header-actions"><button type="button" data-act="clear" title="clear">⌫</button><button type="button" data-act="close" title="close">✕</button></div></div><div class="asobi-term-body"></div><div class="asobi-term-input-row"><span class="asobi-term-prompt">guest@asobi$</span><input class="asobi-term-input" spellcheck="false" autocomplete="off" autocapitalize="off" /></div>';document.body.appendChild(panel);bodyEl=panel.querySelector('.asobi-term-body');inputEl=panel.querySelector('.asobi-term-input');promptEl=panel.querySelector('.asobi-term-prompt');badgeEl=panel.querySelector('.asobi-term-badge');applyTheme(currentTheme);panel.querySelector('[data-act="close"]').addEventListener('click',function(e){e.stopPropagation();closePanel();});panel.querySelector('[data-act="clear"]').addEventListener('click',function(e){e.stopPropagation();clearTerm();focusInput();});inputEl.addEventListener('keydown',function(e){e.stopPropagation();if(e.key==='Enter'){e.preventDefault();const val=inputEl.value;try{const shown=awaitingPassword?'*'.repeat(Math.min(val.length,12)):val;appendLine(promptText()+' '+shown,'cmd');if(!awaitingPassword&&val.trim()){history.push(val);if(history.length>100)history.shift();}histIdx=history.length;inputEl.value='';executeLine(val);updatePromptUI();}catch(err){appendLine('内部エラー: '+(err&&err.message?err.message:String(err)),'err');}finally{setTimeout(focusInput,0);}}else if(e.key==='ArrowUp'){e.preventDefault();if(!history.length)return;histIdx=Math.max(0,histIdx-1);inputEl.value=history[histIdx]||'';}else if(e.key==='ArrowDown'){e.preventDefault();histIdx=Math.min(history.length,histIdx+1);inputEl.value=histIdx>=history.length?'':(history[histIdx]||'');}else if(e.key==='Escape')closePanel();else if(e.key==='l'&&(e.ctrlKey||e.metaKey)){e.preventDefault();clearTerm();}});panel.addEventListener('mousedown',function(e){if(e.target===inputEl)return;if(e.target.closest&&e.target.closest('button, a, input, textarea, select'))return;e.preventDefault();focusInput();});appendLine('Asobi Lab. Terminal v1.3','sys');appendLine('panels で特殊パネル一覧。console / storage / network / dom / info / palette / keys','sys');}
function boot(){try{loadSavedTheme();}catch(e){}try{hookConsole();}catch(e){}try{hookNetwork();}catch(e){}try{buildUI();}catch(e){console.error('AsobiTerminal buildUI',e);}try{updatePromptUI();}catch(e){}window.AsobiTerminal={open:openPanel,close:closePanel,toggle:togglePanel,exec:executeLine,openConsole:openLocalConsole,closeConsole:closeLocalConsole,openStorage:openStorage,openNetwork:openNetwork,openDom:openDom,openInfo:openInfo,openPalette:openPalette,openKeys:openKeys,setTheme:applyTheme,getTheme:function(){return currentTheme;},themes:THEMES.slice()};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
