/**
 * Asobi Lab. Terminal + Local Console v1.2
 * focus-fix: re-focus input after each command; try/catch executeLine
 * Themes: default matrix ubuntu macos powershell cyber cmd dracula nord solarized monokai light
 */
(function () {
  'use strict';
  if (window.__ASOBI_TERMINAL_BOOTED__) return;
  window.__ASOBI_TERMINAL_BOOTED__ = true;

  const BASE = '/asobiseminar';
  const SU_PASSWORD = 'kanrishakengen';
  const SUDO_MS = 5 * 60 * 1000;
  const THEME_KEY = 'asobi-term-theme';
  const THEMES = ['default','matrix','ubuntu','macos','powershell','cyber','cmd','dracula','nord','solarized','monokai','light'];
  const LOG_BUFFER_MAX = 200;

  const FS_TREE = {
    '404.html':'file','favicon.svg':'file','index.html':'file','index2.html':'file',
    'memo.md':'file','samplecss.css':'file','settings.html':'file','sitemap.html':'file',
    'themecolor.json':'file','variable.css':'file','テーマのメモ.txt':'file',
    MENU:{'MENU.css':'file','MENU.js':'file'},
    css:{'404.css':'file','aboutsite.css':'file','asobi-play.css':'file','groupsIndex.css':'file','index-main.css':'file','members.css':'file','one.css':'file','playground.css':'file','programmer.css':'file','settings.css':'file','style.css':'file','three.css':'file','title.css':'file','two.css':'file'},
    gaibu:{'unpkg.css':'file'},
    js:{'404.js':'file','asobi-play.js':'file','autovalue.js':'file','load-css.js':'file','playground.js':'file','setThemeColor.js':'file'},
    json:{'autovalue.json':'file'},
    subpages:{'aboutsite.html':'file','gallery.html':'file','members.html':'file','playground.html':'file',groups:{'englishgame.html':'file','index.html':'file','one.html':'file','programmer.html':'file','three.html':'file','two.html':'file'}},
    terminal:{'terminal.css':'file','terminal.js':'file'}
  };
  const PAGE_MAP = {home:BASE+'/index.html',index:BASE+'/index.html',playground:BASE+'/subpages/playground.html',members:BASE+'/subpages/members.html',groups:BASE+'/subpages/groups/index.html',about:BASE+'/subpages/aboutsite.html',aboutsite:BASE+'/subpages/aboutsite.html',settings:BASE+'/settings.html',gallery:BASE+'/subpages/gallery.html',one:BASE+'/subpages/groups/one.html',two:BASE+'/subpages/groups/two.html',three:BASE+'/subpages/groups/three.html',programmer:BASE+'/subpages/groups/programmer.html',englishgame:BASE+'/subpages/groups/englishgame.html',sitemap:BASE+'/sitemap.html'};

  let isRoot=false,sudoUntil=0,history=[],histIdx=-1,awaitingPassword=false;
  let panel,bodyEl,inputEl,promptEl,badgeEl,toggleBtn,consolePanel,consoleBody,consoleInput;
  let consoleHooked=false,currentTheme='default',logBuffer=[];

  const origConsole={log:console.log.bind(console),info:console.info.bind(console),warn:console.warn.bind(console),error:console.error.bind(console),debug:console.debug?console.debug.bind(console):console.log.bind(console)};

  function hasElevated(){return isRoot||Date.now()<sudoUntil;}
  function promptText(){return hasElevated()?'root@asobi#':'guest@asobi$';}
  function updatePromptUI(){if(!promptEl||!badgeEl)return;const elev=hasElevated();promptEl.textContent=promptText();promptEl.classList.toggle('is-root',elev);badgeEl.textContent=elev?(isRoot?'ROOT':'SUDO'):'guest';badgeEl.classList.toggle('is-root',elev);}
  function focusInput(){if(!inputEl)return;try{inputEl.focus({preventScroll:true});}catch(e){try{inputEl.focus();}catch(e2){}}}
  function appendLine(text,cls){if(!bodyEl)return;const p=document.createElement('div');p.className='asobi-term-line '+(cls||'out');p.textContent=text;bodyEl.appendChild(p);bodyEl.scrollTop=bodyEl.scrollHeight;}
  function clearTerm(){if(bodyEl)bodyEl.innerHTML='';}
  function applyTheme(name){const t=THEMES.includes(name)?name:'default';currentTheme=t;try{localStorage.setItem(THEME_KEY,t);}catch(e){}if(panel){if(t==='default')panel.removeAttribute('data-theme');else panel.setAttribute('data-theme',t);}}
  function loadSavedTheme(){try{const s=localStorage.getItem(THEME_KEY);if(s&&THEMES.includes(s))currentTheme=s;}catch(e){}}

  function buildTreeLines(node,prefix){const lines=[];const keys=Object.keys(node).sort((a,b)=>{const aDir=typeof node[a]==='object',bDir=typeof node[b]==='object';if(aDir!==bDir)return aDir?-1:1;return a.localeCompare(b,'ja');});keys.forEach((k,i)=>{const last=i===keys.length-1;const branch=last?'└── ':'├── ';const next=prefix+(last?'    ':'│   ');if(typeof node[k]==='object'){lines.push(prefix+branch+k+'/');lines.push(...buildTreeLines(node[k],next));}else lines.push(prefix+branch+k);});return lines;}

  function cmdHelp(){appendLine('Asobi Lab. Terminal — コマンド一覧','info');appendLine('  help / clear / ls / pwd / whoami / history / echo / date / uname','out');appendLine('  open <page|url> / su / sudo <cmd> / exit / logout','out');appendLine('  chaos.on|off|status / score / theme.list|set','out');appendLine('  term.theme <name>  見た目12種','out');appendLine('  console.open|close  JS実行ログ','out');appendLine('例: term.theme dracula','sys');appendLine('例: sudo console.open','sys');}
  function cmdLs(){appendLine(BASE+'/','info');buildTreeLines(FS_TREE,'').forEach(l=>appendLine(l,'out'));}
  function cmdOpen(target){if(!target){appendLine('用法: open <page|url>','warn');appendLine('page: '+Object.keys(PAGE_MAP).join(', '),'sys');return;}const key=target.toLowerCase().replace(/^\/+/, '');let url=PAGE_MAP[key];if(!url){if(/^https?:\/\//i.test(target))url=target;else if(target.startsWith('/'))url=target;else if(target.includes('.html')||target.includes('/'))url=BASE+'/'+target.replace(/^\/+/, '');}if(!url){appendLine('見つかりません: '+target,'err');return;}appendLine('open → '+url,'ok');setTimeout(()=>{location.href=url;},280);}
  function cmdChaos(action){const ap=window.AsobiPlay;if(!ap||typeof ap.toggleChaos!=='function'){appendLine('AsobiPlay が未読込です','err');return;}if(action==='on'){ap.toggleChaos(true);appendLine('混沌モード ON','ok');}else if(action==='off'){ap.toggleChaos(false);appendLine('混沌モード OFF','ok');}else if(action==='status'||!action){appendLine('chaos: '+(document.body.classList.contains('asobi-chaos')?'ON':'OFF'),'info');}else appendLine('用法: chaos.on | chaos.off | chaos.status','warn');}
  function cmdScore(){const ap=window.AsobiPlay;if(ap&&typeof ap.getScore==='function')appendLine('遊びスコア: '+ap.getScore()+' pt','ok');else appendLine('遊びスコア: '+(localStorage.getItem('asobi-play-score')||'0')+' pt','ok');}
  function cmdTheme(action,name){if(action==='list'||!action){fetch(BASE+'/themecolor.json').then(r=>r.json()).then(data=>{const themes=data.themes||data;appendLine('利用可能なテーマ:','info');(Array.isArray(themes)?themes:[]).forEach(t=>appendLine('  - '+(t.name||t),'out'));focusInput();}).catch(e=>{appendLine('テーマ一覧の取得に失敗: '+(e&&e.message?e.message:e),'err');focusInput();});return;}if(action==='set'){if(!name){appendLine('用法: theme.set <name>','warn');return;}localStorage.setItem('selectedTheme',name);appendLine('テーマを設定: '+name+'（再読込します）','ok');setTimeout(()=>location.reload(),400);return;}appendLine('用法: theme.list | theme.set <name>','warn');}
  function cmdTermTheme(action,name){if(action==='list'||!action){appendLine('ターミナル見た目 — '+THEMES.length+' 種:','info');THEMES.forEach(t=>appendLine('  - '+t+(t===currentTheme?' ← 現在':''),'out'));appendLine('用法: term.theme <name>','sys');return;}if(action==='set'){if(!name||!THEMES.includes(name)){appendLine('不明: '+(name||'(なし)'),'err');appendLine('利用可能: '+THEMES.join(', '),'sys');return;}applyTheme(name);appendLine('ターミナルテーマ: '+name,'ok');return;}if(THEMES.includes(action)){applyTheme(action);appendLine('ターミナルテーマ: '+action,'ok');return;}appendLine('用法: term.theme list | term.theme <name>','warn');}

  function stringifyArg(a){if(a===null)return 'null';if(a===undefined)return 'undefined';if(typeof a==='string')return a;if(typeof a==='number'||typeof a==='boolean'||typeof a==='bigint')return String(a);if(typeof a==='symbol')return a.toString();if(a instanceof Error)return a.stack||(a.name+': '+a.message);if(typeof a==='function')return '[Function'+(a.name?': '+a.name:'')+']';try{return JSON.stringify(a,function(_k,v){if(typeof v==='bigint')return v.toString()+'n';if(typeof v==='function')return '[Function]';return v;},0);}catch(e){try{return Object.prototype.toString.call(a);}catch(e2){return String(a);}}}
  function iconFor(level){return level==='error'?'✕':level==='warn'?'⚠':level==='info'?'ℹ':'›';}
  function pushConsoleEntry(level,args){const entry={level,args,ts:Date.now()};logBuffer.push(entry);if(logBuffer.length>LOG_BUFFER_MAX)logBuffer.shift();if(!consoleBody)return;renderConsoleEntry(entry);}
  function renderConsoleEntry(entry){if(!consoleBody)return;const el=document.createElement('div');el.className='asobi-console-entry '+entry.level;const icon=document.createElement('span');icon.className='asobi-console-icon';icon.textContent=iconFor(entry.level);el.appendChild(icon);const time=document.createElement('span');time.className='asobi-console-time';const d=new Date(entry.ts);time.textContent=d.toLocaleTimeString('ja-JP',{hour12:false})+'.'+String(d.getMilliseconds()).padStart(3,'0');el.appendChild(time);const msg=document.createElement('span');msg.className='asobi-console-msg';msg.textContent=entry.args.map(stringifyArg).join(' ');el.appendChild(msg);consoleBody.appendChild(el);consoleBody.scrollTop=consoleBody.scrollHeight;}
  function flushLogBufferToUI(){if(!consoleBody)return;consoleBody.innerHTML='';logBuffer.forEach(renderConsoleEntry);}
  function hookConsole(){if(consoleHooked)return;consoleHooked=true;['log','info','warn','error','debug'].forEach(level=>{const mapLevel=level==='debug'?'log':level;console[level]=function(...args){origConsole[level](...args);try{pushConsoleEntry(mapLevel,args);}catch(e){}};});window.addEventListener('error',ev=>{const parts=[];if(ev.message)parts.push(ev.message);if(ev.filename)parts.push('@ '+ev.filename+(ev.lineno!=null?':'+ev.lineno:'')+(ev.colno!=null?':'+ev.colno:''));if(ev.error&&ev.error.stack)parts.push('\n'+ev.error.stack);pushConsoleEntry('error',[parts.join(' ')||'Uncaught Error']);});window.addEventListener('unhandledrejection',ev=>{const r=ev.reason;let msg='UnhandledRejection: ';if(r instanceof Error)msg+=r.stack||(r.name+': '+r.message);else msg+=stringifyArg(r);pushConsoleEntry('error',[msg]);});pushConsoleEntry('info',['Local console attached.']);}
  function openLocalConsole(){ensureConsoleUI();flushLogBufferToUI();consolePanel.classList.add('is-open');appendLine('ローカルコンソールを開きました','ok');if(consoleInput)setTimeout(()=>consoleInput.focus(),50);}
  function closeLocalConsole(){if(consolePanel)consolePanel.classList.remove('is-open');appendLine('ローカルコンソールを閉じました','sys');setTimeout(focusInput,30);}
  function runConsoleEval(code){if(!code.trim())return;pushConsoleEntry('log',['› '+code]);try{const result=(0,eval)(code);if(result!==undefined)pushConsoleEntry('info',[stringifyArg(result)]);}catch(e){pushConsoleEntry('error',[e&&e.stack?e.stack:String(e)]);}}
  function ensureConsoleUI(){if(consolePanel)return;consolePanel=document.createElement('div');consolePanel.className='asobi-console-panel';consolePanel.innerHTML='<div class="asobi-console-header"><span class="asobi-console-label"><span>JS Console</span><span class="asobi-console-live">LIVE</span></span><div style="display:flex;gap:6px"><button type="button" data-act="clear">clear</button><button type="button" data-act="close">✕</button></div></div><div class="asobi-console-body"></div><div class="asobi-console-input-row"><input class="asobi-console-input" placeholder="eval / 式を入力" spellcheck="false" autocomplete="off" /><button type="button" class="asobi-console-run">Run</button></div>';document.body.appendChild(consolePanel);consoleBody=consolePanel.querySelector('.asobi-console-body');consoleInput=consolePanel.querySelector('.asobi-console-input');consolePanel.querySelector('[data-act="close"]').addEventListener('click',closeLocalConsole);consolePanel.querySelector('[data-act="clear"]').addEventListener('click',()=>{logBuffer=[];if(consoleBody)consoleBody.innerHTML='';});consolePanel.querySelector('.asobi-console-run').addEventListener('click',()=>{runConsoleEval(consoleInput.value);consoleInput.value='';});consoleInput.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Enter'){runConsoleEval(consoleInput.value);consoleInput.value='';}if(e.key==='Escape')closeLocalConsole();});}

  function resolveDotted(parts,args){const obj=parts[0],method=parts[1],rest=parts.slice(2).concat(args);if(obj==='console'){if(method==='open'){if(!hasElevated()){appendLine('permission denied: sudo console.open を使用','err');return true;}openLocalConsole();return true;}if(method==='close'){closeLocalConsole();return true;}if(method==='clear'){logBuffer=[];if(consoleBody)consoleBody.innerHTML='';appendLine('console cleared','ok');return true;}appendLine('不明: console.'+method,'err');return true;}if(obj==='chaos'){cmdChaos(method);return true;}if(obj==='theme'){cmdTheme(method,rest[0]);return true;}if(obj==='score'){if(method==='get'||method==='show')cmdScore();else appendLine('用法: score','warn');return true;}if(obj==='term'||obj==='terminal'){if(method==='clear')clearTerm();else if(method==='close')closePanel();else if(method==='open')openPanel();else if(method==='theme'){if(!rest.length||rest[0]==='list')cmdTermTheme('list');else if(rest[0]==='set')cmdTermTheme('set',rest[1]);else cmdTermTheme(rest[0],rest[1]);}else{appendLine('不明: terminal.'+method,'err');}return true;}return false;}

  function executeSingle(raw){const line=String(raw||'').trim();if(!line)return;if(awaitingPassword){awaitingPassword=false;if(line===SU_PASSWORD){isRoot=true;updatePromptUI();appendLine('認証成功。root 権限を取得しました。','ok');}else appendLine('認証失敗','err');return;}if(/^sudo(\s|$)/i.test(line)){const rest=line.replace(/^sudo\s*/i,'').trim();sudoUntil=Date.now()+SUDO_MS;updatePromptUI();appendLine('[sudo] 一時権限を付与（5分）','sys');if(!rest)return;executeSingle(rest);return;}const dottedMatch=line.match(/^([a-zA-Z_][\w]*)\.([a-zA-Z_][\w.]*)(?:\s+(.*))?$/);if(dottedMatch){const obj=dottedMatch[1];const methodPath=dottedMatch[2].split('.');const argStr=(dottedMatch[3]||'').trim();const dArgs=argStr?argStr.split(/\s+/):[];if(resolveDotted([obj].concat(methodPath),dArgs))return;appendLine('不明な属性: '+obj+'.'+methodPath.join('.'),'err');return;}const tokens=[];const reTok=/"([^"]*)"|(\S+)/g;let mTok;while((mTok=reTok.exec(line))!==null){tokens.push(mTok[1]!==undefined?mTok[1]:mTok[2]);}const cmd=(tokens[0]||'').toLowerCase();const args=tokens.slice(1);switch(cmd){case 'help':case '?':cmdHelp();break;case 'clear':case 'cls':clearTerm();break;case 'ls':case 'tree':cmdLs();break;case 'pwd':appendLine(location.pathname,'out');break;case 'whoami':appendLine(hasElevated()?(isRoot?'root':'guest (sudo)'):'guest','out');break;case 'history':if(!history.length)appendLine('(empty)','sys');else history.forEach((h,i)=>appendLine(String(i+1).padStart(3)+'  '+h,'out'));break;case 'echo':appendLine(args.join(' '),'out');break;case 'open':cmdOpen(args[0]);break;case 'su':appendLine('Password:','info');awaitingPassword=true;break;case 'exit':if(isRoot||Date.now()<sudoUntil){isRoot=false;sudoUntil=0;updatePromptUI();appendLine('権限を破棄しました','sys');}else closePanel();break;case 'logout':isRoot=false;sudoUntil=0;updatePromptUI();appendLine('logout','sys');break;case 'chaos':cmdChaos(args[0]);break;case 'score':cmdScore();break;case 'theme':cmdTheme(args[0],args[1]);break;case 'console':if(args[0]==='open'){if(!hasElevated())appendLine('permission denied: sudo console.open','err');else openLocalConsole();}else if(args[0]==='close')closeLocalConsole();else appendLine('用法: console.open | console.close','warn');break;case 'date':appendLine(new Date().toString(),'out');break;case 'uname':appendLine('AsobiLab Terminal · '+navigator.userAgent.split(' ').slice(-2).join(' '),'out');break;case 'reload':appendLine('reloading…','sys');setTimeout(()=>location.reload(),200);break;default:appendLine('command not found: '+cmd,'err');appendLine('help で一覧を表示','sys');}}

  function executeLine(raw){String(raw||'').split(/\s*&&\s*/).forEach(p=>{try{executeSingle(p);}catch(err){appendLine('実行エラー: '+(err&&err.message?err.message:String(err)),'err');}});}
  function openPanel(){if(!panel)return;panel.classList.add('is-open');if(toggleBtn)toggleBtn.classList.add('is-active');setTimeout(focusInput,30);}
  function closePanel(){if(!panel)return;panel.classList.remove('is-open');if(toggleBtn)toggleBtn.classList.remove('is-active');}
  function togglePanel(){if(panel&&panel.classList.contains('is-open'))closePanel();else openPanel();}

  function buildUI(){if(document.querySelector('.asobi-term-toggle'))return;toggleBtn=document.createElement('button');toggleBtn.type='button';toggleBtn.className='asobi-term-toggle';toggleBtn.title='Asobi Terminal';toggleBtn.setAttribute('aria-label','Open terminal');toggleBtn.innerHTML='>_';toggleBtn.addEventListener('click',e=>{e.stopPropagation();togglePanel();});document.body.appendChild(toggleBtn);panel=document.createElement('div');panel.className='asobi-term-panel';panel.innerHTML='<div class="asobi-term-header"><span class="asobi-term-title">Asobi Terminal</span><span class="asobi-term-badge">guest</span><div class="asobi-term-header-actions"><button type="button" data-act="clear" title="clear">⌫</button><button type="button" data-act="close" title="close">✕</button></div></div><div class="asobi-term-body"></div><div class="asobi-term-input-row"><span class="asobi-term-prompt">guest@asobi$</span><input class="asobi-term-input" spellcheck="false" autocomplete="off" autocapitalize="off" /></div>';document.body.appendChild(panel);bodyEl=panel.querySelector('.asobi-term-body');inputEl=panel.querySelector('.asobi-term-input');promptEl=panel.querySelector('.asobi-term-prompt');badgeEl=panel.querySelector('.asobi-term-badge');applyTheme(currentTheme);panel.querySelector('[data-act="close"]').addEventListener('click',e=>{e.stopPropagation();closePanel();});panel.querySelector('[data-act="clear"]').addEventListener('click',e=>{e.stopPropagation();clearTerm();focusInput();});inputEl.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Enter'){e.preventDefault();const val=inputEl.value;try{const shown=awaitingPassword?'*'.repeat(Math.min(val.length,12)):val;appendLine(promptText()+' '+shown,'cmd');if(!awaitingPassword&&val.trim()){history.push(val);if(history.length>100)history.shift();}histIdx=history.length;inputEl.value='';executeLine(val);updatePromptUI();}catch(err){appendLine('内部エラー: '+(err&&err.message?err.message:String(err)),'err');}finally{setTimeout(focusInput,0);}}else if(e.key==='ArrowUp'){e.preventDefault();if(!history.length)return;histIdx=Math.max(0,histIdx-1);inputEl.value=history[histIdx]||'';}else if(e.key==='ArrowDown'){e.preventDefault();histIdx=Math.min(history.length,histIdx+1);inputEl.value=histIdx>=history.length?'':(history[histIdx]||'');}else if(e.key==='Escape')closePanel();else if(e.key==='l'&&(e.ctrlKey||e.metaKey)){e.preventDefault();clearTerm();}});panel.addEventListener('mousedown',e=>{if(e.target===inputEl)return;if(e.target.closest&&e.target.closest('button, a, input, textarea, select'))return;e.preventDefault();focusInput();});appendLine('Asobi Lab. Terminal v1.2','sys');appendLine('help / term.theme (12種) / sudo console.open','sys');}

  function boot(){loadSavedTheme();hookConsole();buildUI();updatePromptUI();window.AsobiTerminal={open:openPanel,close:closePanel,toggle:togglePanel,exec:executeLine,openConsole:openLocalConsole,closeConsole:closeLocalConsole,setTheme:applyTheme,getTheme:()=>currentTheme,themes:THEMES.slice()};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
